mission_manager:
  ros__parameters:
    waypoints:
      # Base camp
      basecamp:
        position:
          x: 4.631
          y: 3.740
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0
        frame_id: "map"
      
      # Room waypoints
      "3410":
        position:
          x: 6.5
          y: 3.9
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 1.0
          w: 0.0
        frame_id: "map"
